version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: hiredesk-postgres
    environment:
      POSTGRES_DB: hiredesk_dev
      POSTGRES_USER: hiredesk_user
      POSTGRES_PASSWORD: hiredesk_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hiredesk_user -d hiredesk_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: hiredesk-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@hiredesk.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data: 